### ISSUE TITLE
vue-template-compiler issue

### ISSUE THREAD

**Issue by mxrlkn** [egoist/styled-vue#9]
Building a nuxt project with this package gives me the error:

```
Vue packages version mismatch:
  
  - vue@2.5.17
  - vue-template-compiler@2.5.22
```

including nuxts version of `vue-template-compiler`  in the projects package.json fixes it.

Shouldn't `vue-template-compiler` be in devDependencies in styled-vue?

**Comment by egoist** [comment]
Nope, that should be a dependency of this package. Just update nuxt and styled-vue to ensure they have the same version of `vue` and `vue-template-compiler`.

**Comment by mxrlkn** [comment]
Updated nuxt from 2.3.4 to 2.4.2. Works thanks!
